<?php

namespace Hoga\La5xunfei;

use Illuminate\Support\ServiceProvider;

class La5xunfeiServiceProvider extends ServiceProvider
{

    /**
     * {@inheritdoc}
     */
    public function boot()
    {
        if ($this->app->runningInConsole()) {
            $this->publishes(
                [
                    __DIR__ . '\..\config\xunfei.php' => config_path('xunfei.php'),
                ],
                'config'
            );
        }
    }

    public function register()
    {
        // parent::register(); // TODO: Change the autogenerated stub
    }
}
