<?php

namespace Hoga\la5xunfei;

use Illuminate\Support\ServiceProvider;

class La5xunfeiServiceProvider extends ServiceProvider
{

    /**
     * {@inheritdoc}
     */
    public function boot()
    {
        if ($this->app->runningInConsole()) {
            dd($this);
            $this->publishes(
                [
                    public_path('vendor/hoga/la5xunfei/config/xunfei.php') => config_path('xunfei.php'),
                ],
                'config'
            );
        }
    }

    public function register()
    {
        // parent::register(); // TODO: Change the autogenerated stub
    }
}
