<?php


namespace ChenJiaJing\XunFeiYun;


use Illuminate\Support\ServiceProvider;

class XFYunServiceProvider  extends ServiceProvider
{

    public function boot()
    {
        $this->publishes([
            __DIR__ . '\..\config\xfyun.php' => config_path('xfyun.php'),
        ]);
    }

    public function  register()
    {
        // parent::register(); // TODO: Change the autogenerated stub
    }
}
